### ISSUE TITLE
[ioRedis] Error

### ISSUE THREAD

**Issue by masterofshapes** [HeliosOrg/SimpleDataIntegration#2]
Following the server setup instructions. Everything goes great till I try and run the "node server.js"  I get the following error:
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1063:14)

Tried on both windows and ubuntu aws instance. Security rules on AWS is allowing access on port 80, and I disabled any firewall when I tried on windows.

**Comment by DennisAXu** [comment]
Can you try running redis-server before running "node server.js"? That should fix it.

**Comment by MiguelDebruyne** [comment]
I'm having the same problem.
I am trying to run this on localhost (MAMP) though since I don't have a AWS (or like) server.

I have followed the _'Server Setup'_ to install the server step by step but to no avail. It has been edited just recently but this doesn't work either. I see you added 

> Run redis-server to start your redis server.

But then I got this error

`zsh: command not found: redis-server`

Is it me or is the tutorial incomplete? :)

**Comment by DennisAXu** [comment]
Ah, so you have to make sure you have redis installed first, which you can do by following [these instructions](http://redis.io/download) or running `brew install redis` if you have Homebrew on Mac. Then, you should be able to run redis-server. Let me know if this works and we'll update the documentation.

**Comment by MiguelDebruyne** [comment]
I have installed redis through homebrew. I started the redis-server and it says it's all fine 

> Running in standalone mode
> Port: 6379
> PID: 994
> Server started, Redis version 3.2.3
> The server is now ready to accept connections on port 6379

On some ports when I do `node server.js` I get nothing, literally. I can see it's doing something but it doesn't finish or break. On others I get `Error: listen EACCES`. `Sudo` does not help in both cases

I don't have a lot of knowledge about ports or these plugins so forgive me for that.

**Comment by DennisAXu** [comment]
No problem, running `node server.js` basically just starts the server. So if you're seeing the server hang, that is expected behavior. You should now be able to communicate to this server via the plugin nodes. When you're running the plugin not in AWS, but on localhost, you should change the port that the server file is [listening on to a number greater than 1024](http://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports). Let me know if this helps/works.

**Comment by ttangGC** [comment]
Thanks for the help Dennis, the plugin is working great for me now!
